// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_email_sender/flutter_email_sender.dart';

Future<void> sendVacantRoomReport(
    List<DocumentReference> propertyRefs, String recipientEmail) async {
  try {
    final firestore = FirebaseFirestore.instance;
    final buffer = StringBuffer();
    int totalVacantRooms = 0;
    final propertyRoomMap = <String, Map<String, int>>{};

    // Process properties in batches to handle Firestore's 'in' query limit of 10
    for (int i = 0; i < propertyRefs.length; i += 10) {
      final batch = propertyRefs.sublist(
          i, i + 10 > propertyRefs.length ? propertyRefs.length : i + 10);

      final querySnapshot = await firestore
          .collection('Room')
          .where('property_id', whereIn: batch)
          .where('room_status', isEqualTo: 'Vacant')
          .get();

      final rooms = querySnapshot.docs;

      if (rooms.isNotEmpty) {
        // Group rooms by property
        for (final room in rooms) {
          final data = room.data();
          final propertyRef = data['property_id'] as DocumentReference?;

          if (propertyRef == null) continue;

          final roomType = data['room_type'] ?? 'Unknown';

          // Get property name (with caching to avoid duplicate fetches)
          final propertyDoc = await propertyRef.get();
          final propertyData = propertyDoc.data() as Map<String, dynamic>?;
          final propertyName = propertyDoc.exists && propertyData != null
              ? (propertyData['property_name'] as String?) ?? 'Unnamed Property'
              : 'Unknown Property';

          // Initialize property entry if not exists
          propertyRoomMap.putIfAbsent(propertyName, () => <String, int>{});

          // Count room types for this property
          propertyRoomMap[propertyName]![roomType] =
              (propertyRoomMap[propertyName]![roomType] ?? 0) + 1;
        }

        totalVacantRooms += rooms.length;
      }
    }

    // Build the report content
    if (totalVacantRooms > 0) {
      buffer.writeln('📊 VACANT ROOM SUMMARY');
      buffer.writeln('=' * 40);
      buffer.writeln('Total Vacant Rooms: $totalVacantRooms\n');

      // Sort properties alphabetically for consistent reporting
      final sortedProperties = propertyRoomMap.keys.toList()..sort();

      for (final propertyName in sortedProperties) {
        final roomTypes = propertyRoomMap[propertyName]!;
        final propertyTotal = roomTypes.values.reduce((a, b) => a + b);

        buffer.writeln('🏠 $propertyName ($propertyTotal vacant rooms)');

        // Sort room types for consistent output
        final sortedTypes = roomTypes.keys.toList()..sort();
        for (final roomType in sortedTypes) {
          buffer.writeln('   • $roomType: ${roomTypes[roomType]} rooms');
        }
        buffer.writeln('');
      }
    } else {
      buffer.writeln(
          '✅ Great news! No vacant rooms found across all properties.');
    }

    final subject =
        'Vacant Room Report - ${DateTime.now().toString().split(' ')[0]}';
    final message = '''
Hello,

Here is your vacant room report for ${DateTime.now().toString().split(' ')[0]}:

${buffer.toString()}

This report was automatically generated by your property management system.

Best regards,
Property Management System
''';

    // Send Email
    await sendEmail(recipientEmail, subject, message);

    // Optional: Log successful execution for debugging
    print('Vacant room report sent successfully to $recipientEmail');
  } catch (e) {
    // Handle errors gracefully
    print('Error generating vacant room report: $e');

    // Send error notification email
    try {
      await sendEmail(recipientEmail, 'Error: Vacant Room Report Failed',
          'An error occurred while generating the vacant room report: $e\n\nPlease contact support if this issue persists.');
    } catch (emailError) {
      print('Failed to send error notification email: $emailError');
    }

    // Re-throw to allow FlutterFlow to handle the error
    throw e;
  }
}

Future<void> sendEmail(String to, String subject, String body) async {
  try {
    final email = Email(
      body: body,
      subject: subject,
      recipients: [to],
      isHTML: false,
    );
    await FlutterEmailSender.send(email);
  } catch (e) {
    print('Email sending failed: $e');
    throw e;
  }
}

// Alternative: HTML formatted email version
Future<void> sendHtmlEmail(String to, String subject, String htmlBody) async {
  try {
    final email = Email(
      body: htmlBody,
      subject: subject,
      recipients: [to],
      isHTML: true,
    );
    await FlutterEmailSender.send(email);
  } catch (e) {
    print('HTML email sending failed: $e');
    throw e;
  }
}
